### PR TITLE
vpu: framebuffer: fix memory leak if we got out of memory

### LINKED ISSUE #122: gst_imx_vpu_framebuffer_array_new: memory leak
If we get out of memory during the loop in 
https://github.com/Freescale/gstreamer-imx/blob/master/src/vpu/framebuffer_array.c#L127

the already allocated memory is not released anymore.

### PR DESCRIPTION
**Pull request by prueckl**
fixes #122

### CODE REVIEW

File: src/vpu/decoder_context.c [hunk 1]
```diff
@@ -64,7 +64,8 @@ static void gst_imx_vpu_decoder_context_finalize(GObject *object)
 	g_mutex_clear(&(decoder_context->mutex));
 	g_cond_clear(&(decoder_context->cond));
 
-	gst_object_unref(GST_OBJECT(decoder_context->framebuffer_array));
+        if(decoder_context->framebuffer_array != NULL)
```
Comment (gibsson) [inline src/vpu/decoder_context.c]: Wrong indentation, please use tabs.

File: src/vpu/framebuffer_array.c [hunk 2]
```diff
@@ -112,6 +115,7 @@ GstImxVpuFramebufferArray * gst_imx_vpu_framebuffer_array_new(ImxVpuColorFormat
 	);
 
 	framebuffer_array->framebuffers = (ImxVpuFramebuffer *)g_slice_alloc(sizeof(ImxVpuFramebuffer) * num_framebuffers);
+        memset(framebuffer_array->framebuffers, 0, sizeof(ImxVpuFramebuffer) * num_framebuffers);
```
Comment (gibsson) [inline src/vpu/framebuffer_array.c]: Same here, please use tabs.
